Repository LucaBrivio183/deliveboo-backend, pull requests merged in 2023-06, with the labels that each got.

#6 ProductSeeder generated by config file
  config/products.php
  database/seeders/ProductSeeder.php
Labels: enhancement

#13 Products crud
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/StoreProductRequest.php
  app/Http/Requests/UpdateProductRequest.php
  app/Models/Product.php
  database/migrations/2023_06_14_143322_create_products_table.php
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/admin/products/index.blade.php
  resources/views/admin/products/show.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partials/message.blade.php
  routes/web.php
Labels: enhancement

#24 Products crud
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/StoreProductRequest.php
  app/Http/Requests/UpdateProductRequest.php
  config/products.php
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/admin/products/index.blade.php
Labels: enhancement

#29 [#28] Bug fixes
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Requests/StoreProductRequest.php
  app/Models/Category.php
  config/categories.php
  config/products.php
  database/migrations/2023_06_14_143221_create_restaurants_table.php
  database/migrations/2023_06_14_143322_create_products_table.php
  database/migrations/2023_06_15_083714_create_categories_table.php
  database/migrations/2023_06_15_105725_add_category_id_foreign_key_to_products_table.php
  database/seeders/CategorySeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ProductSeeder.php
  database/seeders/RestaurantSeeder.php
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/index.blade.php
Labels: bug, enhancement

#27 restaurants create/edit minor feats and fixes
  app/Http/Controllers/Admin/RestaurantController.php
  resources/js/app.js
  resources/js/functions/image_preview.js
  resources/scss/_partials/_form.scss
  resources/scss/app.scss
  resources/views/admin/restaurants/create.blade.php
  resources/views/admin/restaurants/edit.blade.php
Labels: enhancement

#36 restaurants create and edit: minor feats and fixes
  app/Http/Controllers/Admin/RestaurantController.php
  app/Http/Requests/StoreRestaurantRequest.php
  app/Http/Requests/UpdateRestaurantRequest.php
  app/Models/Restaurant.php
  app/Models/Typology.php
  config/restaurants.php
  database/migrations/2023_06_14_143221_create_restaurants_table.php
  database/seeders/DatabaseSeeder.php
  resources/js/functions/image_preview.js
  resources/views/admin/restaurants/create.blade.php
  resources/views/admin/restaurants/edit.blade.php
Labels: enhancement

#40 feat: max typologies per restaurant
  app/Http/Controllers/Admin/RestaurantController.php
  app/Http/Requests/StoreRestaurantRequest.php
  app/Http/Requests/UpdateRestaurantRequest.php
  resources/views/admin/restaurants/create.blade.php
  resources/views/admin/restaurants/edit.blade.php
Labels: enhancement

#41 32 manage the new registered user case
  app/Http/Controllers/Admin/ProductController.php
  resources/views/errors/403.blade.php
  resources/views/errors/404.blade.php
  resources/views/layouts/app.blade.php
Labels: enhancement

#43 feat:restaurant-show-translation
  resources/scss/_partials/_show.scss
  resources/scss/app.scss
  resources/views/admin/restaurants/show.blade.php
Labels: enhancement

#45 feat:orders/order_table-migrations
  app/Models/Order.php
  app/Models/Product.php
  app/Models/Restaurant.php
  app/Models/Typology.php
  app/Models/User.php
  database/migrations/2023_06_15_083506_create_orders_table.php
  database/migrations/2023_06_19_213901_create_order_product_table.php
Labels: enhancement

#47 feat:orders_table -> total_price
  database/migrations/2023_06_15_083506_create_orders_table.php
Labels: enhancement

#50 bug fixes
  app/Providers/RouteServiceProvider.php
  database/migrations/2023_06_15_105725_add_category_id_foreign_key_to_products_table.php
  resources/views/admin/restaurants/index.blade.php
  resources/views/welcome.blade.php
Labels: bug

#56 Creazione API per la visualizzazione del ristorante selezionato e del suo menù
  app/Http/Controllers/Api/RestaurantController.php
  routes/api.php
Labels: enhancement

#59 fix: api controller namespace
  routes/api.php
Labels: bug

#63 61 edit welcome view
  app/Http/Controllers/Admin/RestaurantController.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: enhancement

#67 feat: login password validation
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
Labels: enhancement

#69 user without restaurants redirected to welcome
  app/Http/Controllers/Admin/DashboardController.php
  app/Http/Controllers/Admin/RestaurantController.php
Labels: bug

#74 feat:restaurant_typology_seeder
  app/Models/Restaurant.php
  app/Models/RestaurantTypology.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RestaurantTypologySeeder.php
  resources/views/auth/register.blade.php
Labels: enhancement

#77 73 edit products info
  app/Http/Requests/StoreProductRequest.php
  app/Http/Requests/UpdateProductRequest.php
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/admin/products/index.blade.php
Labels: enhancement

#78 403 errors removed and redirect to 404
  app/Http/Controllers/Admin/ProductController.php
  app/Http/Controllers/Admin/RestaurantController.php
  resources/views/errors/403.blade.php
Labels: enhancement

#80 typo
  app/Http/Controllers/Admin/RestaurantController.php
Labels: bug

#81 fix: resolve categories problem
  app/Http/Requests/StoreProductRequest.php
  app/Http/Requests/UpdateProductRequest.php
  database/migrations/2023_06_15_105725_add_category_id_foreign_key_to_products_table.php
  database/seeders/ProductSeeder.php
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/admin/products/show.blade.php
Labels: bug

#82 Feat: dashboard enhancement
  app/Http/Controllers/Admin/DashboardController.php
  resources/scss/_partials/_dashboard.scss
  resources/views/admin/restaurants/index.blade.php
  resources/views/dashboard.blade.php
Labels: enhancement

#84 fix: index show backoffice
  app/Http/Controllers/Admin/RestaurantController.php
  resources/scss/_partials/_form.scss
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/admin/restaurants/edit.blade.php
  resources/views/admin/restaurants/index.blade.php
  resources/views/dashboard.blade.php
Labels: enhancement

#90 feat: Controller route fixed/ margin body
  app/Http/Controllers/Admin/ProductController.php
  resources/scss/global.scss
  resources/views/admin/products/create.blade.php
  resources/views/admin/products/edit.blade.php
  resources/views/admin/products/show.blade.php
  resources/views/admin/restaurants/create.blade.php
  resources/views/admin/restaurants/edit.blade.php
  resources/views/admin/restaurants/show.blade.php
Labels: enhancement

#92 Added typologies to restaurant api
  app/Http/Controllers/Api/RestaurantController.php
Labels: enhancement

#94 Insert checkout page
  .env.example
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Api/OrderController.php
  app/Http/Controllers/PaymentController.php
  app/Models/OrderProduct.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  routes/api.php
Labels: enhancement

#101 Feat: data entry immagini e prodotti
  app/Models/Product.php
  app/Models/Typology.php
  config/products.php
  config/restaurants.php
  config/typologies.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RestaurantSeeder.php
  database/seeders/TypologySeeder.php
  resources/scss/global.scss
  resources/views/admin/products/edit.blade.php
  resources/views/admin/restaurants/edit.blade.php
  resources/views/dashboard.blade.php
Labels: enhancement

#102 user and restaurant receive an email after order creation
  app/Http/Controllers/Api/OrderController.php
  app/Http/Controllers/Mail/OrderController.php
  app/Mail/RestaurantMail.php
  app/Mail/UserMail.php
  resources/views/emails/new-order.blade.php
  resources/views/emails/order-received.blade.php
Labels: enhancement

#105 fix: backoffice and images rework
  app/Http/Controllers/Admin/DashboardController.php
  app/Http/Controllers/Admin/ProductController.php
  resources/js/functions/image_preview.js
  resources/scss/_partials/_dashboard.scss
  resources/scss/global.scss
  resources/views/admin/products/edit.blade.php
  resources/views/admin/products/show.blade.php
  resources/views/admin/restaurants/edit.blade.php
  resources/views/dashboard.blade.php
Labels: enhancement

#107 100 add stats
  app/Http/Controllers/Admin/StatsController.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/js/functions/chart.js
  resources/views/admin/orders/stats.blade.php
  routes/web.php
Labels: enhancement

#109 fix: general rework dashboard
  app/Http/Controllers/Admin/OrderController.php
  app/Http/Controllers/Admin/ProductController.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RestaurantTypologySeeder.php
  resources/scss/_partials/_dashboard.scss
  resources/scss/_partials/_show.scss
  resources/views/admin/orders/index.blade.php
  resources/views/admin/products/show.blade.php
  resources/views/dashboard.blade.php
Labels: enhancement

#111 feat: orders and order_product seeder
  database/seeders/DatabaseSeeder.php
  database/seeders/OrderSeeder.php
Labels: enhancement

#113 Add more stats
  app/Http/Controllers/Admin/StatsController.php
  resources/js/functions/chart.js
  resources/views/admin/orders/stats.blade.php
Labels: enhancement
